// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtehqdaixoyqsrnocrbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0ZWhxZGFpeG95cXNybm9jcmJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NjQ0NzQsImV4cCI6MjA1NzQ0MDQ3NH0.pKk9Ec2DokTQVCyu0BYaRrkTWpcjR72b__Z-2CH3leM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);